version: "3"
services:
    client:
        build: ./client
        ports:
            - "8888:80"
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - "6001:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-CU8-ubuntu"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SqlExpress!"
            ACCEPT_EULA: "Y"