// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    partial class SpeakerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Models.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "f7fe91db-40ad-433f-9bdf-aa4a193823b0",
                            City = "Vancouver",
                            Email = "aaa@aaa.com",
                            Employer = "Javazon Prime",
                            FirstName = "Tom",
                            LastName = "Day",
                            MobileNumber = "1231231234",
                            Province = "BC",
                            Specialization = "Java"
                        },
                        new
                        {
                            SpeakerId = "b7f204e0-9aae-4fbf-a99c-ea8c95cd9157",
                            City = "Surrey",
                            Email = "bbb@aaa.com",
                            Employer = "Denny's",
                            FirstName = "John",
                            LastName = "Ham",
                            MobileNumber = "1231231234",
                            Province = "BC",
                            Specialization = "Breakfast"
                        },
                        new
                        {
                            SpeakerId = "5b97c8fd-31aa-407a-9e54-36776efd0511",
                            City = "Richmond",
                            Email = "ccc@aaa.com",
                            Employer = "AUDL",
                            FirstName = "Reneil",
                            LastName = "Pascua",
                            MobileNumber = "1231231234",
                            Province = "BC",
                            Specialization = "Ultimate Frisbee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
