version: "3"
services:
    api:
        build: .
        ports:
            - "8888:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-CU8-ubuntu"
        environment:
            SA_PASSWORD: "SqlExpress!"
            ACCEPT_EULA: "Y"